# Nome da aplicação
spring.application.name=devshowcase-api

# Configuração do Banco de Dados H2 (Em Memória)
spring.datasource.url=jdbc:h2:mem:devshowcasedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console (Para visualizar as tabelas no navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate (Criação automática das tabelas)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Configuração da UI do Swagger / OpenAPI 
springdoc.swagger-ui.path=/swagger-ui.html